im:
  tcpPort: 9001
  webSocketPort: 19001
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 3000 # 心跳超时时间 单位毫秒
  brokerId: 1001
  logicUrl: http://127.0.0.1:8000/v1 # Feign RPC 调用业务层
  loginModel: 3
  # 多端同步模式: 1 只允许一端在线，手机/电脑/web 踢掉除了本 client+imei 的设备
  #             2 允许手机/电脑的一台设备 + web 在线 踢掉除了本 client+imei 的非 web 端设备
  #             3 允许手机和电脑单设备 + web 同时在线 踢掉非本 client+imei 的同端设备
  #             4 允许所有端多设备登录 不踢任何设备

  redis:
    mode: single # 单机模式:single 哨兵式:sentinel 集群模式:cluster
    database: 0
    password:
    timeout: 3000 # 超时时间
    poolMinIdle: 4 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(秒)
    poolSize: 10 # 连接池大小
    single: #redis单机配置
      address: 127.0.0.1:6379

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtualHost: /
    userName: admin
    password: admin

  zkConfig:
    zkAddr: 127.0.0.1:2181
    zkConnectTimeOut: 5000