spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/im_core?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8
    username: root

  application:
    name: im-core

appConfig:
  zkAddr: 127.0.0.1:2181 # zk 连接地址
  zkConnectTimeOut: 5000 # zk 超时时间
  imRouteModel: 3 # 路由策略 1.轮询 2.随机 3.一致性hash

# logger 配置
#logging:
#  config: classpath:logback-spring.xml

server:
  port: 8000


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY
  type-aliases-package: com.bantanger.im.domain

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true
